name: Copy issues from starter repo

env: 
  GH_TOKEN: ${{ secrets.TOKEN }}
  STARTER_REPO: https://github.com/bu-ist/id-github-setup

on: 
  workflow_dispatch:

jobs:
    initialize: 
      name: List Issues to JSON
      runs-on: ubuntu-latest
      outputs:
        issues: ${{ steps.get-issues.outputs.issues }}

      steps: 
        - uses: actions/checkout@v3
        - name: List Issues
          id: get-issues
          run: |
           GH_REPO=${{env.STARTER_REPO}} gh issue list -s open --json number,title,body,labels | jq '[ ( .[] | { number: .number, title: .title , body: .body, labels: ( .labels | [ .[].name ] | join(",") )  } ) ]' > issues.json          
           cat issues.json
           {
               echo 'issues<<THIS_IS_THIS_EOF_MARKER'
               cat issues.json
               echo THIS_IS_THIS_EOF_MARKER
           } >> "$GITHUB_OUTPUT"
          
    addIssuesToRepo:
        name: Add issue ( ${{matrix.value.number }}) ( ${{matrix.value.title }})to repo
        runs-on: ubuntu-latest
        needs: [initialize]

        strategy:
          matrix:
            value: ${{ fromJSON(needs.initialize.outputs.ISSUES) }}
        steps:
          - name: Checkout repo
            uses: actions/checkout@v3.5.2
          - name: Create issue
            id: new-issue
            uses: dacbd/create-issue-action@main
            with:
              token: ${{ secrets.CLONEISSUES }}
              title: ${{ matrix.value.title }}
              body: ${{ matrix.value.body }}
              labels: ${{ matrix.value.labels }}
          - run: |
              echo "Copied issue ${{ github.event.inputs.issue_number }} from ${{ env.STARTER_REPO }}/issues/${{ github.event.inputs.issue_number }}" >> "$GITHUB_STEP_SUMMARY"
              echo " to issue ${{ steps.new-issue.outputs.number }} at url ${{ steps.new-issue.outputs.html_url }}" >> "$GITHUB_STEP_SUMMARY"
